### ISSUE TITLE
containers failing to start after upgrade to 3.1.0

### ISSUE THREAD

**Issue by norman-abramovitz** [concourse/concourse#1229]
# Bug Report

After upgrading to 3.1.0 from 3.0.1 we are seeing the following error when running a task.

runc create: exit status 1: container_linux.go:264: starting container process caused "process_linux.go:339: container init caused \"rootfs_linux.go:57: mounting \\\"/var/vcap/data/baggageclaim/volumes/live/668a7846-5839-4b4a-7ff7-67d058144e90/volume\\\" to rootfs \\\"/var/vcap/data/garden/graph/aufs/mnt/a241f57e3e053ebfa8ed0cc06c62e6b350229283cd825b3e223527620ce49d95\\\" at \\\"/var/vcap/data/garden/graph/aufs/mnt/a241f57e3e053ebfa8ed0cc06c62e6b350229283cd825b3e223527620ce49d95/scratch\\\" caused \\\"mkdir /var/vcap/data/garden/graph/aufs/mnt/a241f57e3e053ebfa8ed0cc06c62e6b350229283cd825b3e223527620ce49d95/scratch: permission denied\\\"\""

Also tried recreating the workers and it still failed with the same error.  (bosh recreate workers)

The following can also be handy:

* Concourse version: 3.1.0
* Deployment type (BOSH):
* Infrastructure/IaaS: vsphere
* Browser (if applicable):
* Did this used to work? yes

**Comment by devdavidkarlsson** [comment]
Could this be related to #1231

**Comment by norman-abramovitz** [comment]
Thanks,  I will look into the permission/ownership changes you mentioned and will give feedback.

**Comment by vito** [comment]
Don't think this is related to #1231 as that issue is likely Darwin specific.

@norman-abramovitz Is this fixed by a recreate of the worker? It also seems extremely suspect that it's mounting into the Garden graph. Are you using `rootfs_uri` in your task config?

**Comment by norman-abramovitz** [comment]
I am seeing incorrect owners

drwxr-xr-x 2 4294967294 4294967294 4096 May 15 17:44 

Still working on seeing if I can get things work though.

**Comment by norman-abramovitz** [comment]
Yes, the pipeline is using rootfs_uri.   Upgraded to 3.1.1 and did a Bosh recreate workers.   Still seeing the error.   I will see if we can switch to image_resource

**Comment by AdamDorwart** [comment]
Also seeing the same issue in 3.1.1. Running with ATC in docker and seperate workers using binaries

**Comment by bensullivan** [comment]
We are seeing the permission denied error as well on 3.1.1 that we just deployed

**Comment by vito** [comment]
@bensullivan Can you specify what image you're using for your rootfs? Or better yet, a pipeline or task that reproduces the error?

@julz Any pointers for that error? It looks like Garden-runC is failing to mount its own init binary in, maybe because of weird permissions on `/tmp`?

**Comment by norman-abramovitz** [comment]
docker:///starkandwayne/concourse-go#1.7

**Comment by norman-abramovitz** [comment]
Switched over to use image_resource and Bosh restart workers finally worked on 3.1.1  

rootfs_uri still fails

**Comment by AdamDorwart** [comment]
I've recreated my workers. ATC, and database. This issue is still plaguing my pipelines most of the time.

**Comment by bensullivan** [comment]
Hi @vito - I'm not quite sure what you mean regarding the image we're using for the rootfs...  Are you talking about the image that docker is running on or the container image itself?  I'll give you both...

We run Concourse via Amazon ECS using an EC2 instance based on the [Amazon ECS-Optimised AMI](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-optimized_AMI.html).  This "ECS instance" runs (amongst other things) the AWS ECS container agent alongside docker 1.12.6.  We then run the Concourse web and worker containers on this ECS instance.

The devices available on our ECS instance are:
`[ec2-user@ip-10-139-1-108 ~]$ lsblk
NAME                                                                                         MAJ:MIN   RM  SIZE RO TYPE MOUNTPOINT
xvda                                                                                         202:0      0    8G  0 disk
└─xvda1                                                                                      202:1      0    8G  0 part /
xvdh                                                                                         202:112    0   80G  0 disk /ecs/concourse/worker/work
xvdcz                                                                                        202:26368  0   22G  0 disk
└─xvdcz1                                                                                     202:26369  0   22G  0 part
  ├─docker-docker--pool_tmeta                                                                253:0      0   24M  0 lvm
  │ └─docker-docker--pool                                                                    253:2      0 21.8G  0 lvm
  │   ├─docker-202:1-263237-dc048f955c84f5d855b814e2949a746fffb0190b26e747c914e1bdbfd894f1ef 253:3      0   10G  0 dm
  │   ├─docker-202:1-263237-ec7ad28a9821e7f75d438f999333924b9b4750a8031536316366fc28b3141ff6 253:4      0   10G  0 dm
  │   └─docker-202:1-263237-cf259e335093f9f4002266954f6db541bee4a7984578c6d67b6b78875fb6ab16 253:5      0   10G  0 dm
  └─docker-docker--pool_tdata                                                                253:1      0 21.8G  0 lvm
    └─docker-docker--pool                                                                    253:2      0 21.8G  0 lvm
      ├─docker-202:1-263237-dc048f955c84f5d855b814e2949a746fffb0190b26e747c914e1bdbfd894f1ef 253:3      0   10G  0 dm
      ├─docker-202:1-263237-ec7ad28a9821e7f75d438f999333924b9b4750a8031536316366fc28b3141ff6 253:4      0   10G  0 dm
      └─docker-202:1-263237-cf259e335093f9f4002266954f6db541bee4a7984578c6d67b6b78875fb6ab16 253:5      0   10G  0 dm`

**Comment by norman-abramovitz** [comment]
@bensullivan Do any of your pipeline YAML files contain rootfs_uri.  It is the files you use on fly set-pipeline command.   You could also use 'fly get-pipeline' to get the current pipeline and search the returned data.  The other item you can search for is "image_resource".  In both cases, return the complete stanza.

**Comment by bensullivan** [comment]
Hi @norman-abramovitz 

We use image_resource:

> jobs:
- name: build-engine
  plan:
  - get: sheba-engine-git-repo
    trigger: true
  - task: build
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          email: ci@veriluma.com
          password: xxxx
          repository: verilumaci/maven-3.3.9
          username: verilumaci
      run:
        path: src/deploy/concourse-ci/run-build.sh
        args: []
        dir: sheba-engine-git-repo
      inputs:
      - name: sheba-engine-git-repo
        path: ""
      outputs:
      - name: results
        path: ""
    ensure:
      put: slack-alert
      params:
        always_notify: true
        channel: '#ci'
        text: |-
          $TEXT_FILE_CONTENT

          Check out details of this build result at:
          http://concourse.devtools/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
          or:
          http://concourse.devtools/builds/$BUILD_ID
        text_file: results/message.txt
        username: sheba-engine

Is this what you're after?

Thanks very much for your help

Ben

**Comment by AdamDorwart** [comment]
I've noticed a trend that this appears to only be happening on one of my workers. Again it's a machine that's setup using the 3.1.1 binary

Is there anything I could check on this worker that would help before I destroy it?

**Comment by AdamDorwart** [comment]
So I've re-provisioned the entire system concourse system (Deleted all volumes including DB, started ATC, workers, and DB from scratch).

Interestingly I'm still getting the permission denied issue on the worker on the same physical machine that was giving me issues before. Maybe it's something about the environment?

**Comment by dsyer** [comment]
Not sure if this is relevant for the OP, but I got this same error in 3.1.0 and fixed it by adding an explicit `image_resource` to a task (previously apparently there was a sensible default, but now there isn't).

**Comment by clarafu** [comment]
Having no image specified in the task is equivalent to specifying a blank `rootfs_uri`, so that's the same deprecated code path on Linux.

However we didn't anticipate this change breaking `rootfs_uri`, so we'll have to investigate that.

In any case, unless you've got a *really* great reason to use `rootfs_uri`, you should be using `image_resource`, which was introduced all the way back in v0.72.0 to replace and deprecate `rootfs_uri` (formerly known as `image`).

**Comment by vito** [comment]
I'm seeing 3 different issues here now:

* The original, caused by `rootfs_uri` usage, which is now fixed.
* @bensullivan's mount issue, which may be from bad permissions on `/work`? You could try `chmod 0777`ing it - if it's `0700` unprivileged containers won't be able to access their rootfses.
* @AdamDorwart's mount issue, which looks like Concourse might just not be running in a privileged container

It's unclear to me which of these are genuinely regressions with 3.1.0 or if this issue is just turning into a collection of unrelated deployment problems.

In any case, the original issue (`rootfs_uri` breakage) is resolved by switching to `image_resource`. `rootfs_uri` has been documented as "deprecated/unsupported/danger zone" since February of 2016, so it no huge surprise that it broke, but we'll investigate that.

For everyone else, could you reopen separate issues with steps to reproduce, and mention whether it's a new regression with 3.1.0? We cover a wide breadth of platforms and deployment schemes in our testing and everything's green on our side, so we'll need some threads to pull on to investigate each issue. (Thanks @bensullivan for already providing the ECS template and deployment info - that's a great start!)

**Comment by bensullivan** [comment]
@vito - no problems - thanks for the feedback.  We've rolled back to 2.7.7 and are back in business.  I'll try what you suggest with `0777` on the worker work folder.  I'll also put together a hello world pipeline to try and remove some more variables from what we're seeing and help with the troubleshooting.  Cheers
