### ISSUE TITLE
Docker resources and tasks with private CAs are broken

### ISSUE THREAD

**Issue by DRuggeri** [concourse/concourse#1340]
# Bug Report

Internal registries signed by a private CA (when you don't want to disable all validation with insecure_registries) are broken. I've verified it works in 3.1.1 and 3.1.0 but no prior or older versions.

I assume this is a side effect or regression after 3.1.1, but a guess makes me think it's related to the introduction of (( params )) in 3.2.0.

When using 3.3.0, I can only reproduce the issue when
* A task is using in-line config instead of from file
* ... or is a custom resource
* The config is using [docker-image](https://github.com/concourse/docker-image-resource)
  * with CA certs defined
  * with client certs defined

When attempting to set the following pipeline (on v3.3.0) works. However, removing the comments in the CA certs section results in `failed to save config: json: error calling MarshalJSON for type *atc.LoadTaskConfig: json: unsupported type: map[interface {}]interface {}`. It seems that the source schema when inside a config element in the pipeline permits only key/value or key/array pairs.

*EDIT*
I have also found that custom resource types using docker-image are also broken. The error there (not seen when set-pipeline is called, but rather when the resource attempts to check) is `json: unsupported type: map[interface {}]interface {}`. With fly, forcing a check simply returns a 500.

**Sample Pipeline**
````
jobs:
- name: hello
  plan:
  - task: hithere
    config:
      platform: linux

      image_resource:
        type: docker-image
        source:
          repository: alpine
#Remove these hashes to become sad
#          ca_certs:
#            - domain: foobar
#              cert: abc
      run:
        path: sh
        args: [ '-c', 'echo Hello' ]
````

**Comment by DRuggeri** [comment]
A quick question... since 3.3.0 [added a change to DB encryption](https://concourse.ci/downloads.html#v3.3.0) which we are using, does that prevent fallback to 3.1.1?

**Comment by chendrix** [comment]
You are correct that that migration and the migration to add task caching prevent fallback to 3.1.1

This issue should be addressed in the next release, I've attached it to the 3.3.x milestone.

**Comment by mariash** [comment]
The issue is actually related to any nested resource configuration https://github.com/concourse/concourse/issues/1345

**Comment by jsiebens** [comment]
@mariash We are also using private CAs and after upgrading to 3.3.1 (released June 30) we are still getting this error when setting our pipelines

**Comment by clarafu** [comment]
@jsiebens what part of your pipeline config is broken using your private CAs?

**Comment by DRuggeri** [comment]
I can confirm that after upgrading to 3.3.1, I'm still unable to set pipelines using the docker image resource with nested configs. The pipeline snippet I shared in the initial report can still reproduce the problem

**Comment by jtarchie** [comment]
@DRuggeri, thanks for the report, again. We've been able to narrow down the [issue to YAML decoding](https://github.com/go-yaml/yaml/issues/139), which is causing the 'map[interface{}]interface{}` issue.

It was not directly related to #1345. Same cause (the library) just a different different area of the code base.

**Comment by DRuggeri** [comment]
OK, cool. Thanks for the heads up. Sounds like you have a handle on it, but if there's any info I can share, feel free to drop a line.
