### ISSUE TITLE
Kubernetes as first-class citizen, tested and used in prod somewhere

### ISSUE THREAD

**Issue by vito** [concourse/concourse#1731]
Requirements for "Tested":
- [ ] Add jobs to the main Concourse pipeline to extensively test the Helm Chart #2743
- [ ] Create a [topgun](https://github.com/concourse/topgun) equivalent for the Helm chart #2742 

Requirements for "used in prod somewhere" (scenarios probably covered by Topgun tests): 
* Drain (retire) with timeout
  * Alternatively, support for ephemeral worker state (concourse/concourse#1457)

**Comment by gajwani** [comment]
I was googling around for this about an hour ago, heh. 

Saw that there's a `helm` chart for this [here](https://github.com/kubernetes/charts/tree/master/stable/concourse), which was going to be my starting point, but it sounds like you might have other plans. Others are apparently trying to use it: #936, #937

**Comment by vito** [comment]
@gajwani We're still exploring our options, but yes, we want to ensure Concourse works well running in kubernetes.

**Comment by timrchavez** [comment]
@gajwani We're still evaluating our options, but yah, we want to ensure Concourse runs well in kubernetes :)

**Comment by ebabani** [comment]
This makes me happy!

**Comment by william-tran** [comment]
There's been some sadness around worker lifecycle in k8s (eg https://github.com/concourse/concourse/issues/1255#issuecomment-330353898) whose resulting tears have been crystallized into some new chart features, but depending on how "ephemeral worker state (concourse/concourse#1457)" shakes out, those features I added could break, or might not be needed anymore. Please keep us updated of these plans, especially changes to how `retire-worker` works, or if any fixes are made to the behaviour I see in my #1255 comment.

**Comment by ahume** [comment]
I started documenting the current state of our Concourse on Kubernetes: https://gist.github.com/ahume/d56699f3eb2292dbbc1ba3825d44e4b5

Hope is to compare/contrast approach with others.

**Comment by SEJeff** [comment]
Any more work on this?

**Comment by jama-pivotal** [comment]
I think the first step will be to start pulling in the Helm chart and deploying it as a part of our main `develop` pipelines on https://ci.concourse-ci.org/ . This would probably be a new flavor of `topgun` and `testflight` on k8s

**Comment by pclalv** [comment]
that concourse runs its own containers with garden is a deal-breaker for my team. it'd be nice if concourse could delegate the scheduling of containers to kubernetes itself. jenkins, for example, offers this support via the [kubernetes-plugin](https://github.com/jenkinsci/kubernetes-plugin)

**Comment by pivotal-jamie-klassen** [comment]
We investigated this a bit -- created a cluster on GKE, deployed helm-tiller, installed the concourse chart. The deployments in the helm chart all use the `concourse/concourse` image on dockerhub, which gets published with each release. The latest tag for that image corresponds to `3.14.1`. If we check out the version of `testflight` corresponding to the `3.14.1` release, we find that testflight assumes the deployed atc is run with the `--no-really-i-dont-want-any-auth` flag. However, there is no option in the helm chart's `values.yml` that corresponds to this flag being passed to the `web` pod. For now, then, testflight will always fail because it cannot login. At least as far as we can tell.

Once 3.14.2 (or 4.0 more likely) is released, then we stand a chance of running testflight against the helm chart, since `testflight` starts to assume the presence of the `ATC_USERNAME` and `ATC_PASSWORD` environment variables.

**Comment by vito** [comment]
To anyone waiting with bated breath, we've started on this last week and things are humming along. We're picking up @william-tran's helm chart and figuring out what it takes to have our tests run against release candidates in our pipeline.

@pclalv Sounds like https://github.com/concourse/rfcs/pull/2 is relevant to your interests! This issue however is first focusing on simply deploying Concourse *to* Kubernetes and ensuring that's well-understood/supported with today's worker architecture. The linked RFC is all about exploring a future model where we use Kubernetes itself for pipeline workloads.

**Comment by leosunmo** [comment]
I'd just like to bump this up a bit as Concourse seems like such an excellent alternative to a messy Jenkins or a costly Travis installation with the ability of giving to much power to developers in a safe way. The fact that it's not sitting very comfortably in Kubernetes, utilising its strengths, is a bit of a bummer at the moment. I'd love to see ephemeral Jobs and/or Pods being spun up on spare resources running my CI/CD!

**Comment by ajbouh** [comment]
I strongly agree with this sentiment! I tried to figure out how to deploy concourse on kubernetes to do exactly this before I realized that it was just not how the current implementation works. I'm probably going to just use prow in the meantime until I can find an actual CI project that supports this. Really hoping it's concourse though :)

**Comment by topherbullock** [comment]
Changed the description for the original issue to cover more criteria for testing the Helm chart

**Comment by cirocosta** [comment]
Hey @topherbullock ,

I remember we had some issues regarding workers seeing their disks full.

Do you think exploring how we could leverage the use of metrics in this scenario would be useful to consider? I wonder if we could eventually do something like we did for `periodic` and other test environments (given that they end up in a fully deployed environment, they had metrics as well).

thx!

**Comment by william-tran** [comment]
Issues have cropped up in 4.x that make operating on k8s even more difficult, and I won't move ahead on upgrading from 3.14.1 without things actually becoming easier on k8s. 

- #2757 
- #2753 
- #1919 

At the very least, detecting the right fatal errors so that a bad worker can be shut down, alongside leveraging ephemeral workers e.g by registering with a timestamped name could improve things enough.

**Comment by darwin67** [comment]
Hello! Just curious if there are any progress on this?

**Comment by cirocosta** [comment]
Hi @darwin67 ,

We have implemented several test cases that focus on the boundaries of the Helm chart (see https://github.com/concourse/concourse/tree/27097c93f25e84cd3f346f81d8013b550ca01a93/topgun/k8s).

I'm considering this issue closed as:

- there are jobs in the pipeline for running the necessary tests
- it's used somewhere ([`hush-house`](https://github.com/concourse/hush-house))

Even though we're not doing the continuous-deployment of it in the main pipeline, there's already a separate issue for it that now lives under the Test Pilot Pair (for non-pivots - that's a pair takes the responsibility of both handling internal interrupts and operating our environments)  backlog.

Thanks!

**Comment by darwin67** [comment]
@cirocosta 
Got it. We won't be using Helm so technically running concourse in kubernetes still won't be an option for us yet.

I've also been following the `K8s Runtime` project and I see it's closed. Is this continued in the `Runtime interface` or `Resources V2` project?

**Comment by ddadlani** [comment]
@darwin67 It is continued in the Runtime Interface project (https://github.com/concourse/concourse/projects/16). As part of developing a Kubernetes runtime for Concourse, we also plan to clean up the existing runtime interface.
