### ISSUE TITLE
Vault multi-line values are not supported - no support for ssh-keys through vault?

### ISSUE THREAD

**Issue by EugenMayer** [concourse/concourse#1820]
# Bug Report

i am adding my ssh key using `vault write secret/concourse/main/git_kw_ci_sshkey value=@key`
while key being a file in the PWD with the ssh private key.

i did try to consume bot ways:

```
      private_key: |
        ((git_kw_ci_sshkey))
```
and

```
      private_key: ((git_kw_ci_sshkey))
```

Both time getting a

```
resource script '/opt/resource/check []' failed: exit status 1

stderr:
Error loading key "/tmp/git-resource-private-key": invalid format
```

Am i writing / retrieving it the wrong way or is there yet no way to support ssh keys from the vault? Using `value read secret/concourse/main/git_kw_ci_sshkey` the returned value is just fine

**Comment by EugenMayer** [comment]
Fixed it, works with 

```
private_key: |
        ((git_kw_ci_sshkey))
```

and `vault write secret/concourse/main/git_kw_ci_sshkey value=@key`

**Comment by JasonMorgan** [comment]
@EugenMayer I'm still having that issue and haven't figured out what exactly to do here.  Any amount of spacing I put into the pipeline definition fil still gets resolved back to just 1 indent.  Do you mind expanding a bit more on this fix?

**Comment by EugenMayer** [comment]
@JasonMorgan how do you write those into the vault

**Comment by JasonMorgan** [comment]
One, thanks for the quick response!

two:
```
vault write /concourse/ISDE-Cloud/git ssh_key=@.ssh/concourse_git_key

vault read -format json /concourse/ISDE-Cloud/git | jq .data.ssh_key
"-----BEGIN RSA PRIVATE KEY-----\jhdkf...fdjhb\n-----END RSA PRIVATE KEY-----\n"

```

Relevant part of my pipeline def:

```
    private_key: |
            ((git.ssh_key))
```

**Comment by EugenMayer** [comment]
well i use the former option, so 👍 
` vault write secret/concourse/${team}/git_kw_ci_sshkey value=@key`


and reading it

```private_key: ((git_kw_ci_sshkey))```

so that one differs, try that one.

**Comment by JasonMorgan** [comment]
Any chance it the "\n" replacements that I get when injecting the key into vault?  I tried putting the string that I get from `vault read -format json /concourse/ISDE-Cloud/git | jq .data.ssh_key` right in the pipeline file and got the same error.

**Comment by JasonMorgan** [comment]
Anyway, switching to using value then changing my pipeline to use: `((git))` didn't seem to make any impact.

**Comment by M0nsieurChat** [comment]
Unfortunately, we ran into the same issue.  
Didn't find any workaround yet

**Comment by JasonMorgan** [comment]
Yeah it was on the resource. I the resource I was using didn't behave correctly but other resources ran without issue. Can you share out what resource you're having the issue with?

**Comment by M0nsieurChat** [comment]
Hello !
This problem is now solved. We had to hijack the resource container to find how was the formatting of the private key : it contained two extra whitespace character at the beginning of each new line of the private key

The explanation is that we migrated from a YAML file (that was passed along the `-l /path/to/credentials.yml` flag) and copy/pasted this private key as is inside a new text file before uploading it to Vault ; the private key kept the YAML escapment at each new line.

Removing the two extra whitespaces at the beginning of each line did it for us.

I hope it will solve your as well !
