### ISSUE TITLE
Insufficient subnets

### ISSUE THREAD

**Issue by mwilliams-ct** [concourse/concourse#293]
We are working on a very large pipeline (order hundreds of resources and jobs). To try and make this smooth, we have setup three workers on AWS and usually don't see more than 600 containers. However, we are fairly often seeing the error "insufficient subnets remaining in the pool". 

This is not a great error message as it is unclear what the solution is. Would it be possible to improve the error or at least add a note to the man pages explaining a solution? After some searching, https://github.com/concourse/concourse/issues/235 might provide the solution for most people suffering this

**Comment by xoebus** [comment]
At the moment the error coming from Garden is just a string to us. We don't know if it's "insufficient subnets remaining in the pool" or "panic: everything is on fire". In order to provide a better message we'd need to know more about the error or even better we'd be able to use descriptive help text from the Garden error itself.

/cc @julz @willpragnell Could we get some rich Garden errors, pretty please? :blush:

**Comment by piyush0101** [comment]
We are using the concourse standalone binary and running our concourse setup in docker containers with docker-compose. We frequently run into 'insufficient subnets in pool' error and have to restart concourse to resolve the issue. 

Is there a way to increase the subnets limit for concourse standalone binary?

**Comment by kalverra** [comment]
I'm running into a similar issue as @piyush0101, only not even restarting concourse will clean up all these seemingly old and dead containers.

I'm running the concourse docker container setup found here: https://hub.docker.com/r/meteogroup/concourse-ci/

Previously, everything was working fine, however, after going through some testing, the error message
```insufficient subnets remaining in the pool
```
has been popping up relentlessly. Running
```fly -t tag workers```
shows me my containers are at 256 and this seems to be the max. I wonder why concourse isn't cleaning up after itself in this instance? My pipeline is fairly small (2 resources and a job) so I can't imagine these are all actually active containers. Any experience / insight?

**Comment by vito** [comment]
@kalverra Next time it happens could you check the worker logs? Maybe it's failing to delete containers?

**Comment by kalverra** [comment]
@vito seems like it, could you give me instructions / a link on how to check those? It seems the fly CLI only allows me to list the workers and their containers

**Comment by vito** [comment]
@kalverra it goes to stdout of the worker process

**Comment by EcofitBrendan** [comment]
We're also running into the issue on a near-constant basis. 

Our setup at the moment is all on AWS with a m4.large running the web instance and an auto-scaling group of m4.larges running our workers. Unfortunately, this bug causes our jobs to fail well before our instances would ever trigger auto-scaling.

Attached is the log output from a worker, I've truncated it to a single occurrence but it does come up quite frequently. If you'd like more of the logs let me know.
[concourse-worker-293-truncated.log.zip](https://github.com/concourse/concourse/files/316888/concourse-worker-293-truncated.log.zip)

**Comment by vito** [comment]
@EcofitBrendan The more interesting logs would probably come earlier than that if it's from containers failing to destroy.

You may also want to try 1.3 if you haven't already, which improves the balancing of containers across workers.

**Comment by kalverra** [comment]
Here we go, happened after Concourse ran 50 builds. Here's the output from ```fly -t tag workers```:

```
name          containers  platform  tags
df60b394f9a4  256         linux     none
```

No containers are currently running, and just one worker.

Here's a dump of the logs from spinning up the web service to where the error seemed to happen.

[log.txt.tar.gz](https://github.com/concourse/concourse/files/316945/log.txt.tar.gz)

**Comment by vito** [comment]
@kalverra same issue with those logs; it captures the subnet error but not the history leading up to it, which is probably where the answer lives

**Comment by kalverra** [comment]
Here's logs of spinning up web and the workers beginning good tasks

[log.txt.tar.gz](https://github.com/concourse/concourse/files/317007/log.txt.tar.gz)

**Comment by EcofitBrendan** [comment]
I moved my environment into 1.3 and it seems to be cleaning up containers as expected (ran 12 builds, only 45 containers listed by fly workers).

One thing I did notice, I tried to do an in-place upgrade of a worker from 1.2 to 1.3, and in the process of trying to blow away the worker directory I ran into stale file handle errors. After investigating for a bit I opted to just rebuild the worker from scratch rather than use the existing instance. I don't know if this could be related to the issue, but thought it worth mentioning.

**Comment by vito** [comment]
@kalverra Looking at the logs, I'm seeing failed destroys, and from their error it looks like this may be fixed by 1.3's switch to Guardian (and all the cleanup surrounding that). Could you try upgrading?

**Comment by zachgersh** [comment]
@vito - it actually isn't fixed with an upgrade to guardian. We are running
the runc backend and ran out of subnets the other day.

**Comment by vito** [comment]
@zachgersh are you on the same team as @kalverra ? it depends on the issue you're seeing whether 1.3 will fix it or not. "insufficient subnets" could be caused by all sorts of things.

**Comment by APShirley** [comment]
We're also unexpectedly hitting the subnet limit, and after investigating, we have way more containers than we think we should, and it's unclear if concourse knows about them to the extent that it should.

Notice that `fly workers` and `fly containers` deeply disagree re: "the number of containers there are."
```
± ap+ds |master U:1 ✗| → fly -t runtime-ci workers
targeting https://runtime.ci.cf-app.com

name                                  containers  platform  tags
5e2ca663-2fc5-4f4c-b2ed-cedaae2372f1  226         linux     none
63223c63-1a97-499a-9ebb-844ca53b2373  246         linux     none
6d62a602-e1e8-42ff-b3a9-556835f74164  245         linux     none
76636ef6-7ad4-4a1c-a6a2-6d6243b4bf83  230         linux     none
a9328354-8aa4-4b72-83d6-6b7eb94b701f  253         linux     none
bedae717-3a9a-4066-9acc-daf75faa033d  1           linux     none
fa951e2e-1ae0-4225-8cc3-32579898f950  7           linux     vsphere
fc5c9a1c-e5fe-4c53-9473-b6f2e7d52457  219         linux     none

± ap+ds |master U:1 ✗| → fly -t runtime-ci containers | wc -l
     290
```
(FYI, the one with 1 container is a new worker we added to alleviate the immediate issue while we investigated.)

We jumped on the bosh director to run some curls on the workers, where we found that garden's `/containers` endpoint gave us the same numbers as the `workers` output was reporting. We hunted around for a container handle returned by garden that wasn't being reported by `fly containers`, and found this charmer:

```
{
  "MappedPorts": [],
  "State": "active",
  "Events": null,
  "HostIP": "10.254.1.45",
  "ContainerIP": "10.254.1.46",
  "ExternalIP": "10.10.48.17",
  "ContainerPath": "/var/vcap/data/garden/depot/fcdfb535-b05d-4fc1-499a-9f39c5f94318",
  "ProcessIDs": null,
  "Properties": {
    "user": "root",
    "garden.network.host-ip": "10.254.1.45",
    "garden.network.external-ip": "10.10.48.17",
    "garden.network.container-ip": "10.254.1.46",
    "garden.grace-time": "300000000000",
    "concourse:volumes": "[\"69755e98-27bd-4ea3-5798-909947bbc843\",\"48fa2e8b-6529-4cd7-4ad2-a85a0d7b0603\"]",
    "concourse:volume-mounts": "{\"69755e98-27bd-4ea3-5798-909947bbc843\":\"/tmp/build/get\"}",
    "concourse:resource-result": "{\n  \"version\": {\n    \"digest\": \"sha256:39c6f25008da16ae4f93cdf0d66f6a2bf1a3568483f0db5c7e874151d033c568\"\n  },\n  \"metadata\": [\n    {\n      \"name\": \"image\",\n      \"value\": \"sha256:17f5f\"\n    }\n  ]\n}\n",
    "concourse:resource-process": "f1dfeda7-a9ad-4518-7856-e92d6c6ece6b",
    "kawasaki.bridge-interface": "wbrdg-0afe012c",
    "kawasaki.container-interface": "wm5en6ntnrkq-1",
    "kawasaki.dns-servers": "",
    "kawasaki.host-interface": "wm5en6ntnrkq-0",
    "kawasaki.iptable-inst": "m5en6ntnrkq",
    "kawasaki.iptable-prefix": "w--",
    "kawasaki.mtu": "1500",
    "kawasaki.subnet": "10.254.1.44/30"
  }
}
```

Interesting point: the `garden.grace-time` is five minutes. We tried again seven minutes later, and it was there and unchanged, still unknown to `fly containers`.

We can recreate our workers, though we already think we have more than we should need. The numbers reported by `fly containers` seem sane to us, and we were able to account for everything with reasonable estimates of our check containers and recent failing builds. We were gonna' open a new issue, but it sounds like other people here are seeing similar issues.

**Comment by vito** [comment]
@APShirley That also sounds symptomatic of failed container destroying. Could you check the worker logs?

**Comment by JesseTAlford** [comment]
Here's some logs off the worker that seem relevant. I am going to go digging for more, but here's this:
```
{"timestamp":"1467307694.320688486","source":"guardian","message":"guardian.api.garden-server.reaping","log_level":1,"data":{"grace-time":"5m0s","handle":"439fe751-56c1-4683-6d64-e9adddf07a56","session":"3.1"}}
{"timestamp":"1467307694.320779800","source":"guardian","message":"guardian.destroy.start","log_level":1,"data":{"handle":"439fe751-56c1-4683-6d64-e9adddf07a56","session":"536558"}}
{"timestamp":"1467307694.321565628","source":"guardian","message":"guardian.destroy.started","log_level":1,"data":{"handle":"439fe751-56c1-4683-6d64-e9adddf07a56","session":"536559"}}
{"timestamp":"1467307694.321593285","source":"guardian","message":"guardian.destroy.state.started","log_level":1,"data":{"handle":"439fe751-56c1-4683-6d64-e9adddf07a56","session":"536559.1"}}
{"timestamp":"1467307694.334722519","source":"guardian","message":"guardian.destroy.state.finished","log_level":1,"data":{"handle":"439fe751-56c1-4683-6d64-e9adddf07a56","session":"536559.1"}}
{"timestamp":"1467307694.334757090","source":"guardian","message":"guardian.destroy.state","log_level":1,"data":{"handle":"439fe751-56c1-4683-6d64-e9adddf07a56","session":"536559","state":{"Pid":16517,"Status":"running"}}}
{"timestamp":"1467307694.334787369","source":"guardian","message":"guardian.destroy.kill.started","log_level":1,"data":{"handle":"439fe751-56c1-4683-6d64-e9adddf07a56","session":"536559.2"}}
{"timestamp":"1467307694.348384619","source":"guardian","message":"guardian.destroy.kill.finished","log_level":1,"data":{"handle":"439fe751-56c1-4683-6d64-e9adddf07a56","session":"536559.2"}}
{"timestamp":"1467307694.348430395","source":"guardian","message":"guardian.destroy.lookup.started","log_level":1,"data":{"handle":"439fe751-56c1-4683-6d64-e9adddf07a56","session":"536559.3"}}
{"timestamp":"1467307694.348462820","source":"guardian","message":"guardian.destroy.lookup.finished","log_level":1,"data":{"handle":"439fe751-56c1-4683-6d64-e9adddf07a56","session":"536559.3"}}
{"timestamp":"1467307694.402323246","source":"guardian","message":"guardian.create.containerizer-create.watch.done","log_level":1,"data":{"handle":"439fe751-56c1-4683-6d64-e9adddf07a56","session":"536342.3.4"}}
{"timestamp":"1467307694.404214382","source":"guardian","message":"guardian.api.garden-server.reaping","log_level":1,"data":{"grace-time":"5m0s","handle":"7dbaf9a3-6983-4b1d-606a-7b5180205ee6","session":"3.1"}}
{"timestamp":"1467307694.404304981","source":"guardian","message":"guardian.destroy.start","log_level":1,"data":{"handle":"7dbaf9a3-6983-4b1d-606a-7b5180205ee6","session":"536560"}}
{"timestamp":"1467307694.405119181","source":"guardian","message":"guardian.destroy.started","log_level":1,"data":{"handle":"7dbaf9a3-6983-4b1d-606a-7b5180205ee6","session":"536561"}}
{"timestamp":"1467307694.405159235","source":"guardian","message":"guardian.destroy.state.started","log_level":1,"data":{"handle":"7dbaf9a3-6983-4b1d-606a-7b5180205ee6","session":"536561.1"}}
{"timestamp":"1467307694.423828125","source":"guardian","message":"guardian.destroy.state.finished","log_level":1,"data":{"handle":"7dbaf9a3-6983-4b1d-606a-7b5180205ee6","session":"536561.1"}}
{"timestamp":"1467307694.423867226","source":"guardian","message":"guardian.destroy.state","log_level":1,"data":{"handle":"7dbaf9a3-6983-4b1d-606a-7b5180205ee6","session":"536561","state":{"Pid":16458,"Status":"running"}}}
{"timestamp":"1467307694.423918009","source":"guardian","message":"guardian.destroy.kill.started","log_level":1,"data":{"handle":"7dbaf9a3-6983-4b1d-606a-7b5180205ee6","session":"536561.2"}}
{"timestamp":"1467307694.439319134","source":"guardian","message":"guardian.destroy.kill.finished","log_level":1,"data":{"handle":"7dbaf9a3-6983-4b1d-606a-7b5180205ee6","session":"536561.2"}}
{"timestamp":"1467307694.439357042","source":"guardian","message":"guardian.destroy.lookup.started","log_level":1,"data":{"handle":"7dbaf9a3-6983-4b1d-606a-7b5180205ee6","session":"536561.3"}}
{"timestamp":"1467307694.439385653","source":"guardian","message":"guardian.destroy.lookup.finished","log_level":1,"data":{"handle":"7dbaf9a3-6983-4b1d-606a-7b5180205ee6","session":"536561.3"}}
{"timestamp":"1467307694.441476345","source":"guardian","message":"guardian.destroy.destroy.started","log_level":1,"data":{"handle":"439fe751-56c1-4683-6d64-e9adddf07a56","session":"536559.4"}}
{"timestamp":"1467307694.441708326","source":"guardian","message":"guardian.destroy.destroy.finished","log_level":1,"data":{"handle":"439fe751-56c1-4683-6d64-e9adddf07a56","session":"536559.4"}}
{"timestamp":"1467307694.441732168","source":"guardian","message":"guardian.destroy.finished","log_level":1,"data":{"handle":"439fe751-56c1-4683-6d64-e9adddf07a56","session":"536559"}}
{"timestamp":"1467307694.473721504","source":"guardian","message":"guardian.layer-already-deleted-skipping","log_level":1,"data":{"error":"could not find image: no such id: c7d4afe956d396c49b88822a39d44ff765a2d841bfea3087f87fd277be9995be","graphID":"439fe751-56c1-4683-6d64-e9adddf07a56","id":"439fe751-56c1-4683-6d64-e9adddf07a56"}}
{"timestamp":"1467307694.473789454","source":"guardian","message":"guardian.destroy.finished","log_level":1,"data":{"handle":"439fe751-56c1-4683-6d64-e9adddf07a56","session":"536558"}}
```

**Comment by mariash** [comment]
Looking at logs provided by @JesseTAlford all of containers that are reported by garden but are missing in fly coming from containers executing `/opt/resource/in`. They all have this in atc logs (only info level logs available):

```
{"timestamp":"1467282693.473058701","source":"atc","message":"atc.syncer.build-docker-images:scheduler.tick.scheduling.build-latest.scheduling.do.get.init-with-cache.created","log_level":1,"data":{"build-id":258517,"build-name":"7","container":"d8e44bcd-b80c-4375-747b-e756e16482bf","job":"build-destroy-infrastructure-docker-image","name":"destroy-infrastructure-pipeline-image","session":"4.10.110031.42.2.1.4.2.2"}}
```

And garden logs:

```
{"timestamp":"1467282692.921061993","source":"guardian","message":"guardian.create.start","log_level":1,"data":{"handle":"d8e44bcd-b80c-4375-747b-e756e16482bf","session":"513038"}}
{"timestamp":"1467282692.921102285","source":"guardian","message":"guardian.create.network.started","log_level":1,"data":{"handle":"d8e44bcd-b80c-4375-747b-e756e16482bf","session":"513038.1","spec":""}}
{"timestamp":"1467282692.925738335","source":"guardian","message":"guardian.layer-already-deleted-skipping","log_level":1,"data":{"error":"could not find image: no such id: 1b440be2fe575907943c95889547edf4692ef7355616de4f340c7c8da641c212","graphID":"40028a69-d21b-4141-6e05-3b2eade71484","id":"40028a69-d21b-4141-6e05-3b2eade71484"}}
{"timestamp":"1467282692.925783157","source":"guardian","message":"guardian.destroy.finished","log_level":1,"data":{"handle":"40028a69-d21b-4141-6e05-3b2eade71484","session":"513036"}}
{"timestamp":"1467282692.926394701","source":"guardian","message":"guardian.create.network.config-create","log_level":1,"data":{"config":{"HostIntf":...
{"timestamp":"1467282692.926464796","source":"guardian","message":"guardian.create.network.finished","log_level":1,"data":{"handle":"d8e44bcd-b80c-4375-747b-e756e16482bf","session":"513038.1","spec":""}}
{"timestamp":"1467282692.926494122","source":"guardian","message":"guardian.create.gc.start","log_level":1,"data":{"handle":"d8e44bcd-b80c-4375-747b-e756e16482bf","session":"513038.2"}}
{"timestamp":"1467282692.926520586","source":"guardian","message":"guardian.create.gc.finished","log_level":1,"data":{"handle":"d8e44bcd-b80c-4375-747b-e756e16482bf","session":"513038.2"}}
{"timestamp":"1467282692.926538467","source":"guardian","message":"guardian.create.containerizer-create.start","log_level":1,"data":{"handle":"d8e44bcd-b80c-4375-747b-e756e16482bf","session":"513038.3"}}
{"timestamp":"1467282692.960450411","source":"guardian","message":"guardian.create.containerizer-create.depot-create.started","log_level":1,"data":{"handle":"d8e44bcd-b80c-4375-747b-e756e16482bf","session":"513038.3.1"}}
{"timestamp":"1467282692.960669279","source":"guardian","message":"guardian.create.containerizer-create.depot-create.finished","log_level":1,"data":{"handle":"d8e44bcd-b80c-4375-747b-e756e16482bf","session":"513038.3.1"}}
{"timestamp":"1467282692.960694075","source":"guardian","message":"guardian.create.containerizer-create.lookup.started","log_level":1,"data":{"handle":"d8e44bcd-b80c-4375-747b-e756e16482bf","session":"513038.3.2"}}
{"timestamp":"1467282692.960712910","source":"guardian","message":"guardian.create.containerizer-create.lookup.finished","log_level":1,"data":{"handle":"d8e44bcd-b80c-4375-747b-e756e16482bf","session":"513038.3.2"}}
{"timestamp":"1467282692.960733652","source":"guardian","message":"guardian.create.containerizer-create.start.started","log_level":1,"data":{"bundle":"/var/vcap/data/garden/depot/d8e44bcd-b80c-4375-747b-e756e16482bf","handle":"d8e44bcd-b80c-4375-747b-e756e16482bf","session":"513038.3.3"}}
{"timestamp":"1467282693.372423887","source":"guardian","message":"guardian.create.containerizer-create.start.finished","log_level":1,"data":{"bundle":"/var/vcap/data/garden/depot/d8e44bcd-b80c-4375-747b-e756e16482bf","handle":"d8e44bcd-b80c-4375-747b-e756e16482bf","session":"513038.3.3"}}
{"timestamp":"1467282693.372473240","source":"guardian","message":"guardian.create.containerizer-create.finished","log_level":1,"data":{"handle":"d8e44bcd-b80c-4375-747b-e756e16482bf","session":"513038.3"}}
{"timestamp":"1467282693.372529507","source":"guardian","message":"guardian.create.created","log_level":1,"data":{"handle":"d8e44bcd-b80c-4375-747b-e756e16482bf","session":"513038"}}
{"timestamp":"1467282693.372548580","source":"guardian","message":"guardian.api.garden-server.create.created","log_level":1,"data":{"request":{"Handle":"","GraceTime":0,"RootFSPath":"raw:///var/vcap/data/baggageclaim/volumes/live/12266b35-cbd1-4d44-59cc-e74310688047/volume","BindMounts":[{"src_path":"/var/vcap/data/baggageclaim/volumes/live/fa68c52f-c217-4368-7942-d8bebfd8cae5/volume","dst_path":"/tmp/build/get","mode":1}],"Network":"","Privileged":true,"Limits":{"bandwidth_limits":{},"cpu_limits":{},"disk_limits":{},"memory_limits":{}}},"session":"3.1.996102"}}
{"timestamp":"1467282693.372787952","source":"guardian","message":"guardian.create.containerizer-create.watch.watching","log_level":1,"data":{"handle":"d8e44bcd-b80c-4375-747b-e756e16482bf","session":"513038.3.4"}}
{"timestamp":"1467282693.380645990","source":"guardian","message":"guardian.api.garden-server.get-properties.got-properties","log_level":1,"data":{"handle":"d8e44bcd-b80c-4375-747b-e756e16482bf","session":"3.1.996104"}}
{"timestamp":"1467282693.465006351","source":"guardian","message":"guardian.api.garden-server.get-property.failed","log_level":2,"data":{"error":"property does not exist: concourse:resource-result","handle":"d8e44bcd-b80c-4375-747b-e756e16482bf","session":"3.1.996105"}}
{"timestamp":"1467282693.465924025","source":"guardian","message":"guardian.api.garden-server.get-property.failed","log_level":2,"data":{"error":"property does not exist: concourse:resource-process","handle":"d8e44bcd-b80c-4375-747b-e756e16482bf","session":"3.1.996106"}}
{"timestamp":"1467282693.469418526","source":"guardian","message":"guardian.run.started","log_level":1,"data":{"handle":"d8e44bcd-b80c-4375-747b-e756e16482bf","path":"/opt/resource/in","session":"513039"}}
{"timestamp":"1467282693.469481945","source":"guardian","message":"guardian.run.lookup.started","log_level":1,"data":{"handle":"d8e44bcd-b80c-4375-747b-e756e16482bf","path":"/opt/resource/in","session":"513039.1"}}
{"timestamp":"1467282693.469545364","source":"guardian","message":"guardian.run.lookup.finished","log_level":1,"data":{"handle":"d8e44bcd-b80c-4375-747b-e756e16482bf","path":"/opt/resource/in","session":"513039.1"}}
{"timestamp":"1467282693.469581842","source":"guardian","message":"guardian.run.exec.start","log_level":1,"data":{"handle":"d8e44bcd-b80c-4375-747b-e756e16482bf","id":"d8e44bcd-b80c-4375-747b-e756e16482bf","path":"/opt/resource/in","session":"513039.2"}}
{"timestamp":"1467282693.469609022","source":"guardian","message":"guardian.run.exec.prepare.start","log_level":1,"data":{"handle":"d8e44bcd-b80c-4375-747b-e756e16482bf","id":"d8e44bcd-b80c-4375-747b-e756e16482bf","path":"/opt/resource/in","session":"513039.2.1"}}
{"timestamp":"1467282693.485941410","source":"guardian","message":"guardian.run.exec.prepare.finished","log_level":1,"data":{"handle":"d8e44bcd-b80c-4375-747b-e756e16482bf","id":"d8e44bcd-b80c-4375-747b-e756e16482bf","path":"/opt/resource/in","session":"513039.2.1"}}
{"timestamp":"1467282693.486043930","source":"guardian","message":"guardian.run.exec.execrunner.start","log_level":1,"data":{"handle":"d8e44bcd-b80c-4375-747b-e756e16482bf","id":"d8e44bcd-b80c-4375-747b-e756e16482bf","path":"/opt/resource/in","pid":"52c6996a-b33f-4a0d-5e21-5253fbe7ce1a","session":"513039.2.2"}}
{"timestamp":"1467282693.539085388","source":"guardian","message":"guardian.run.exec.execrunner.finished","log_level":1,"data":{"handle":"d8e44bcd-b80c-4375-747b-e756e16482bf","id":"d8e44bcd-b80c-4375-747b-e756e16482bf","path":"/opt/resource/in","pid":"52c6996a-b33f-4a0d-5e21-5253fbe7ce1a","session":"513039.2.2"}}
{"timestamp":"1467282693.539167404","source":"guardian","message":"guardian.run.exec.finished","log_level":1,"data":{"handle":"d8e44bcd-b80c-4375-747b-e756e16482bf","id":"d8e44bcd-b80c-4375-747b-e756e16482bf","path":"/opt/resource/in","session":"513039.2"}}
{"timestamp":"1467282693.539201021","source":"guardian","message":"guardian.run.finished","log_level":1,"data":{"handle":"d8e44bcd-b80c-4375-747b-e756e16482bf","path":"/opt/resource/in","session":"513039"}}
{"timestamp":"1467282693.539240599","source":"guardian","message":"guardian.api.garden-server.run.spawned","log_level":1,"data":{"handle":"d8e44bcd-b80c-4375-747b-e756e16482bf","id":"52c6996a-b33f-4a0d-5e21-5253fbe7ce1a","session":"3.1.996107","spec":{"Path":"/opt/resource/in","Dir":"","User":"root","Limits":{},"TTY":null}}}
{"timestamp":"1467282812.376277208","source":"guardian","message":"guardian.api.garden-server.run.exited","log_level":1,"data":{"handle":"d8e44bcd-b80c-4375-747b-e756e16482bf","id":"52c6996a-b33f-4a0d-5e21-5253fbe7ce1a","session":"3.1.996107","status":0}}
```

**Comment by piyush0101** [comment]
We upgraded to 1.3 and this issues seemed to have been resolved.

However, we upgraded to 1.4 today and the issue seems to be happening again.

**Comment by colstrom** [comment]
Can confirm. I'm also running `1.4.0` (from standalone binaries) and seeing this issue. I've adjusted the `--garden-network-pool` parameter on the worker process. Will report if it resolves.

**Comment by vito** [comment]
may want to try 1.4.1 - there was a bug leading to a container explosion
that was fixed

**Comment by piyush0101** [comment]
Still seeing this issue on `1.4.1`. Containers don't seem to be cleaning up. Is there any more information I can provide here? logs etc?

**Comment by vito** [comment]
Worker logs are what is most useful when debugging this. Preferably large timespans of them, leading up to the issue, not just after. May want to eyeball them to make sure they don't contain sensitive info first.

**Comment by colstrom** [comment]
Not seeing subnet issues on `1.4.1` so far.

**Comment by jfrank-pivotal** [comment]
FYI, we've seen this on 1.4.1 despite the container reaping/retention improvements.  We didn't have the chance to get a container count but it's on a fairly large deployment.

**Comment by zhanggbj** [comment]
We are still seeing this issue on 1.5.1. FYI.

**Comment by mattcui** [comment]
Is there an easy way to clean up contains? After monitor restart or system reboot, I saw it rebuilt these containers in /var/vcap/data/garden/depot. Thanks.

**Comment by vito** [comment]
I'm going to just close this issue as there's not a lot of actionable information and it's become kind of a dumping ground. Many issues have been fixed in the timespan that his issue has been open.

"Insufficient subnets" is akin to "out of memory" or "out of disk" - it's an error explaining the current state, not how it got there. It's something you could see even if everything is operating normally: you may just need more containers than your workers support. The resolution is the same as with any other resource limit - either scale up or look for evidence of a leak, e.g. failed container deletions, more containers existing than they should (`fly containers` vs. `fly workers` discrepancy). If it looks like there's a leak, those kinds of details will be critical in allowing us to fix it or delegate to the correct team (possibly Guardian).

Thanks everyone for trying to help out, I just think this issue's run its course.

@mattcui I'm not sure there's an easy way to clean that stuff up. Given that you're using BOSH I would just recreate the VM. You don't wanna be messing around on instances and manually fixing them much.
