### ISSUE TITLE
Failed to authenticate: missing "username" claim with concourse 6.7.3

### ISSUE THREAD

**Issue by tkallenberg-tw** [concourse/concourse#6431]
## Summary

Hi concourse team

We updated our concourse from version 6.6.0 to 6.7.3 but after that, we are unable to login with our SSO. We are using Onelogin as a provider with the oidc connector. When we try to log in through Onelogin we get the message: 

Failed to authenticate: missing "username" claim

Our Oidc configuration worked so far like this (with some injected parameters):

`--oidc-client-id="$${ONELOGIN_CLIENT_ID}" \
  --oidc-client-secret="$${ONELOGIN_CLIENT_SECRET}" \
  --oidc-scope="groups" \
  --main-team-oidc-group=${onelogin_team} \
  --oidc-issuer=${onelogin_issuer} \
  --oidc-display-name=${onelogin_display_name}
`
Currently we rolled back to version 6.7.2 which seems to work without any issue.

We are aware that for version 6.7.3 an breaking change was announced. However we miss some insights about how to mitigate it.

Thank you very much looking into this. It would help us a lot.

## Steps to reproduce

* Use Onelogin as SSO provider with the OIDC Connector (version 2)
* try to login

## Expected results

Login should work.

## Actual results

Login does not work with OIDC, getting the message: Failed to authenticate: missing "username" claim

## Additional context

Please ask if you need more.

## Triaging info

* Concourse version: 6.7.3
* Browser (if applicable): Firefox 84.0.1 / latest Chrome
* Did this used to work? Yes, it also works with 6.7.2

**Comment by xtremerui** [comment]
Hi, in your OIDC flags are you setting a key to `username`? Also in the Onelogin returing claims, is there a `name` or `username` field?

The error is likely coming from these lines https://github.com/concourse/dex/blob/13cd495873aa655533c7db7322c68ea108d046c7/connector/oidc/oidc.go#L338-L345
since `name` or whatever username key you configured is now mandatory.

**Comment by xtremerui** [comment]
For the configure with `--oidc-scopes`, if you are trying to use groups matching, there is a bug https://github.com/concourse/concourse/issues/6435

**Comment by xtremerui** [comment]
@tkallenberg-tw is your issue resolved now? FYI we are going to release a patch version to fix OIDC connector. So if there is anything you want to add to the release then please let us know. Thx!

**Comment by tkallenberg-tw** [comment]
Hi @xtremerui, sorry for the late response.

Our issue is not yet resolved as we went for version 6.7.2 and did not touch it since then. However I can give you some more info on our configuration. So basically the configuration is the one we pasted in the issue description. We have no other configuration passed to concourse.
We however tried before with the option `--oidc-user-name-key` to user, name or username and the error was still there.

We also had a look at the oidc provider from onelogin and there (https://developers.onelogin.com/openid-connect/api/provider-config) it looks like there is no username claim available.
Our suspicion was that the username claim is requested somewhere else in the code and is just not found in our claims.

We will wait for the 6.7.4 release and give it then another shot to see if it will work again.

**Comment by xtremerui** [comment]
Without configuring --oidc-user-name-key, the default key is `name`, which should be available in the claims returned by onelogin based on the doc you posted. 

Is it possible that the user you tried to login with onelogin doesn't have name configured thus in the returned claims the field is empty or missing? Since it is mandatory now, you will need to use `--oidc-user-name-key` to configure the username key to another field that is `ALWAYS` available and it is better also that the field is unique in the auth provider. For example, `sub` or `email` in your case.

**Comment by taylorsilva** [comment]
@tkallenberg-tw 6.7.4 is out! Let us know if you're able to get it working with that version.

**Comment by rikkuness** [comment]
I've a similar but perhaps different issue. Since upgrading from 6.7.2 to 6.7.4 I get `Failed to authenticate: missing "email_verified" claim`. Digging into it more it seems that my IDP (Azure AD) does not provide an `"email_verified"` claim in their tokens.

It seems there is a configuration option to disable checking for this in dex, but I don't think I can pass this configuration down from skymarshal without it also being added as an OIDCFlags item in there right?

**Comment by xtremerui** [comment]
@rikkuness no concourse doesn't provide a way to config the `insecureSkipEmailVerified`. 

However in your case you can config `--oidc-scope` to exclude `email` scope to bypass the check (noted it might cause your IDP to not return email claim anymore).

**Comment by scottietremendous** [comment]
@tkallenberg-tw @rikkuness - Curious if you've had a chance to upgrade to [v6.7.5](https://github.com/concourse/concourse/releases/tag/v6.7.5) and if this has resolved the issue for you.

**Comment by rikkuness** [comment]
I'm many months late to respond, apologies about that. I've just upgraded all the way to v7.4.0 and hit the same issue still.

I tried as @xtremerui suggested and excluded the `email` scope, so I've that flag set to `openid,profile` and that then still fails to authenticate me but instead with 
```
Internal Server Error
Failed to authenticate: missing "email" claim
```

**Comment by mhp-borisbojic** [comment]
We just updated all the way from concourse 6.1.0 up to 6.7.8 without big issues.

The only issue we have is the one that what initially created by @tkallenberg-tw ... which doesn't seem to be resolved with 6.7.8, yet? We can't use Onelogin OIDC with the error message `Internal Server Error
Failed to authenticate: missing "username" claim`.

Our parameters are:

```/usr/local/concourse/bin/concourse web \
  --tsa-authorized-keys=/opt/concourse/tsa_authorized_keys \
  --tsa-host-key=/opt/concourse/tsa_host_key \
  --session-signing-key=/opt/concourse/session_signing_key \
  --bind-port=xxxx \
  --external-url=${external_url} \
  --add-local-user="${basic_auth_username}:$${BASIC_AUTH_PASSWORD}" \
  --main-team-local-user=${basic_auth_username} \
  --oidc-client-id="$${ONELOGIN_CLIENT_ID}" \
  --oidc-issuer=${onelogin_issuer} \
  --oidc-display-name=${onelogin_display_name} \
  --oidc-client-secret="$${ONELOGIN_CLIENT_SECRET}" \
  --oidc-scope="groups" \
  --main-team-oidc-group=${onelogin_team} \
  --postgres-host=${postgres_host} \
  --postgres-user=${postgres_user} \
  --postgres-password="$${POSTGRES_PASSWORD}" \
  --postgres-sslmode=require \
  --aws-secretsmanager-region=${region} \
  --aws-secretsmanager-team-secret-template=xxx \
  --aws-secretsmanager-pipeline-secret-template=xxx \
  --log-level=debug
```

**Comment by mhp-borisbojic** [comment]
Edit: We were able to fix it by

1. providing an global env variable (CONCOURSE_OIDC_USER_NAME_KEY) and 
2. adding--oidc-user-name-key=email to the concourse web command

**Comment by taylorsilva** [comment]
# Issue Bankruptcy

This issue is being closed as part of 2025's **Issue Bankruptcy** declaration. [See here for details](https://blog.concourse-ci.org/posts/2025-01-06-concourse-2024-review/)

If you think this issue still has merit then feel free to open a new issue and reference this one.
