### ISSUE TITLE
No space left on device error

### ISSUE THREAD

**Issue by gerhard** [concourse/concourse#79]
A Docker image build is failing in a Concourse job:

```
scons: *** [mongostat] No space left on device
scons: *** [mongooplog] No space left on device
scons: *** [mongotop] No space left on device
collect2: error: ld returned 1 exit status
scons: *** [build/linux2/ssl/mongo/mongofiles] Error 1
```

There is plenty of disk space on the worker nodes, this must be a limit imposed in Garden. Any idea on how we might increase it?

**Comment by robdimsdale** [comment]
If you're using v57 or later, you will want to set the worker property `garden.btrfs_store_size_mb` to something like 90% of the worker's ephemeral disk usage, if you haven't already done that.

**Comment by drnic** [comment]
After setting that and deploying; you need to "bosh recreate worker/0" I think

**Comment by gerhard** [comment]
We're still on v50, just about to upgrade to v58. Will give `garden.btrfs_store_size_mb` a try and report back. Cheers @robdimsdale

**Comment by vito** [comment]
You were probably hitting the limit that used to be enforced by the Docker image resource; that should be fixed in 0.58 which removes the limit (the only enforced one then being `garden.btrfs_store_size_mb`).

**Comment by gerhard** [comment]
After the upgrade to v58, had to specify the `garden.btrfs_store_size_mb` property & re-create the workers. So far, so good. Cheers for the input!

**Comment by gerhard** [comment]
OK, so the issue is back. I've set `garden.btrfs_store_size_mb` to **20480** which is 20GB. Compiling Mongo cannot require more than 20GB, surely. This is what `df -h` returns:

```
/dev/xvda1      2.8G  1.4G  1.3G  53% /
none            4.0K     0  4.0K   0% /sys/fs/cgroup
udev            3.7G  4.0K  3.7G   1% /dev
tmpfs           748M  344K  748M   1% /run
none            5.0M     0  5.0M   0% /run/lock
none            3.7G     0  3.7G   0% /run/shm
none            100M     0  100M   0% /run/user
/dev/xvdb2       23G   22G     0 100% /var/vcap/data
tmpfs           1.0M   20K 1004K   2% /var/vcap/data/sys/run
/dev/loop0      120M  1.6M  115M   2% /tmp
/dev/loop1       20G  4.4G   15G  24% /var/vcap/data/garden/btrfs_graph
cgroup          3.7G     0  3.7G   0% /tmp/garden-/cgroup
```

What exactly controls the disk space that a given garden container is allowed to use?

**Comment by vito** [comment]
Any way to tell what the process is actually trying to do? Maybe it's running out of some other resource (e.g. shared memory). Have you observed resource usage as it's running?

**Comment by gerhard** [comment]
After it burns half a forest in user CPU time, it starts flushing to /dev/xvdb and iowait goes through the roof. It writes for a couple of minutes and then stops with the above error. `/dev/xvdb2` grows only marginally, maybe by 1%, so there's plenty of disk space left, same for all other mounts. Those were my observations on v50. I will watch closely again on v58 and come back with more detailed info.

What makes it really difficult to troubleshoot this is that I don't have access to the Docker daemon building this image or, even better, an REPL environment so that I can poke around in that context to understand what is actually happening.

**Comment by vito** [comment]
@gerhard Have you tried [`hijack`](http://concourse.ci/fly-cli.html#fly-intercept)? e.g. `fly hijack -p pipelinename -j jobname -n build-step-name` should get you in the container.

**Comment by gerhard** [comment]
That would be great if hijack actually worked. On v0.59.0, it works half the time with one-off builds, hardly ever with regular builds.

I don't have a build configuration to run a one-off job with fly, this is what I have in the pipeline config:
```
- name: ccp-base-docker-image
  plan:
    - get: ccp-infrastructure
    - put: ccp-docker-image
      params:
        build: ccp-infrastructure/containers/ccp_dev
        cache: true
```

What build config should I provide to run the above job as a one-off?

**Comment by vito** [comment]
Hijack works within 5 minutes of the build finishing (or however long you configure it in your deployment). There's no difference between one-offs and builds from the pipeline. The command you want to run there is `fly hijack -p <pipeline-name> -j ccp-base-docker-image -n ccp-docker-image sh`.

**Comment by gerhard** [comment]
Downloading the latest fly cli fixed hijacking. I'm wondering whether it would be worth keeping the cli version in sync with the concourse release. I had v0.0.1 installed for which hijack didn't work consistently, now that I've downloaded v0.0.1 from Concourse web, it works just fine.

**Comment by vito** [comment]
Yep right now the version reported by fly is meanlingless; `fly sync` is the source of truth. We'll fix that pretty soon.

**Comment by gerhard** [comment]
Nice, I will remember to run that every time Concourse gets upgraded.

**Comment by gerhard** [comment]
After sync-ing fly from the latest Concourse, I could troubleshoot this properly.

It turns out that compiling MongoDB 2.6.10 requires ~50GB. This made the Docker build go through:

```
- name: worker
  properties:
    garden:
      btrfs_store_size_mb: 100000

...

resource_pools:
- name: workers
  cloud_properties:
    instance_type: m4.large
    ephemeral_disk:
      size: 120000 # in MB
      type: gp2
```

**Comment by pidile007** [comment]
i am facing disk space issue, please assist.  thanks..

i am trying to backup ops manager and elastic runtime tile from our Pivotal systems.

**Comment by andy-plutoflume** [comment]
FWIW - because those using the binaries directly cannot set `garden.btrfs_store_size_mb` I think the trick here is to override the following settings with a script of your choice to set the correct size.

```
      --baggageclaim-btrfs-bin=                          Path to btrfs binary (default: btrfs) [$CONCOURSE_BAGGAGECLAIM_BTRFS_BIN]                                                                                                                                 
          --baggageclaim-mkfs-bin=                           Path to mkfs.btrfs binary (default: mkfs.btrfs) [$CONCOURSE_BAGGAGECLAIM_MKFS_BIN]                                    
```
