### ISSUE TITLE
Always logging at debug level in docker images.

### ISSUE THREAD

**Issue by ese** [concourse/concourse#950]
# Bug Report

* Concourse version: 2.7.0
* Deployment type (BOSH/Docker/binary): Docker

TSA logs are always debug even if you set with `$CONCOURSE_LOG_LEVEL: fatal` or `--log-level fatal`

You can reproduce using this docker-compose.yaml and looking `concourse_concourse-web_1` logs
```ỳaml
concourse-db:
  image: postgres:9.5
  environment:
    POSTGRES_DB: concourse
    POSTGRES_USER: concourse
    POSTGRES_PASSWORD: changeme
    PGDATA: /database

concourse-web:
  image: concourse/concourse
  links: [concourse-db]
  command: web
  ports: ["8080:8080"]
  volumes: ["./keys/web:/concourse-keys"]
  environment:
    CONCOURSE_BASIC_AUTH_USERNAME: concourse
    CONCOURSE_BASIC_AUTH_PASSWORD: changeme
    CONCOURSE_EXTERNAL_URL: "${CONCOURSE_EXTERNAL_URL}"
    CONCOURSE_LOG_LEVEL: fatal
    CONCOURSE_POSTGRES_DATA_SOURCE: |-
      postgres://concourse:changeme@concourse-db:5432/concourse?sslmode=disable

concourse-worker:
  image: concourse/concourse
  privileged: true
  links: [concourse-web]
  command: worker
  volumes: ["./keys/worker:/concourse-keys"]
  environment:
    CONCOURSE_TSA_HOST: concourse-web
```

**Comment by billimek** [comment]
Confirming this on my end.  a 10-day old concourse web component had a 23GB logfile deep within the bowels of docker.  Turning down logging via $CONCOURSE_LOG_LEVEL still results in ATC debug-level stuff spewing out.

**Comment by vito** [comment]
Fixed by https://github.com/concourse/tsa/commit/a801dcdcb0b75a91c19946b49ed531b35f6e0c40 - should be in 2.8.0.

**Comment by bacoboy** [comment]
@vito will this also fix the logging level in `concourse/guardian`?  I have it set to `error` in 2.7.0 and still seeing buckets of `info` (level:1) messages from guardian like so:
```
Mar 15 14:44:07 ip-10-0-75-139 concourse[1286]: {"timestamp":"1489589047.043397427","source":"guardian","message":"guardian.run.exec.execrunner.read-exit-fd","log_level":1,"data":{"handle":"cfa873ac-7eb1-4ef7-641c-82c619b04675","id":"cfa873ac-7eb1-4ef7-641c-82c619b04675","path":"/opt/resource/check","session":"44219.2.2"}}
```

**Comment by vito** [comment]
@bacoboy The flag for Garden is separate as we embed their binary within ours under its own namespace. You'll want `CONCOURSE_GARDEN_LOG_LEVEL` (consult `--help` to be sure).

**Comment by bacoboy** [comment]
Thanks I'll check it out.  Might want to update the docs with all the LOG_LEVEL parameters.  I got literally 1 hit in google on that string and it wasn't concourse documentation :)  Thanks!  Looking forward to 2.8!

**Comment by vito** [comment]
@bacoboy Yea, we lean on `--help` and having descriptions for each flag; it'd be too much maintenance to repeat everything in the docs. When in doubt, run `<cmd> --help`.
